SPLIT_KEYBOARD    = yes
NKRO_ENABLE       = yes
ENCODER_ENABLE    = yes
AUDIO_ENABLE      = no
BOOTLOADER        = rp2040
RGBLIGHT_ENABLE   = no
OLED_ENABLE       = yes
RGB_MATRIX_ENABLE = yes
LEADER_ENABLE     = yes
PROGRAMMABLE_BUTTON_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes

# MOUSEKEY_ENABLE      = yes
# EXTRAKEY_ENABLE      = yes
# COMBO_ENABLE         = yes
# CAPS_WORD_ENABLE     = yes
# DYNAMIC_MACRO_ENABLE = yes
# KEY_LOCK_ENABLE      = yes

# UNICODE_ENABLE       = no
# TAP_DANCE_ENABLE     = no
# MAGIC_ENABLE         = no
# BOOTMAGIC_ENABLE     = no
# CONSOLE_ENABLE       = no
# AUTO_SHIFT_ENABLE    = no
